### ISSUE TITLE
Error after finishing scan

### ISSUE THREAD

**Issue by borondics** [OpenModHub/MirrorScan#12]
We need to fix these errors that happen after finishing a scan and also when trying to save a file.

```
  File "C:\Users\Neaspec\Desktop\PROGRAMY\MirrorScan-master\mirrorApp.py", line 501, in scan_complete
    if self.scan_map.Nz == 1:
       ^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'scan_map'
Traceback (most recent call last):
  File "C:\Users\Neaspec\Desktop\PROGRAMY\MirrorScan-master\mirrorApp.py", line 537, in save_data
    np.savetxt(fname, M.T,
  File "C:\Users\Neaspec\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\npyio.py", line 1563, in savetxt
    raise ValueError('fname must be a string or file handle')
ValueError: fname must be a string or file handle
```

**Comment by ngergihun** [comment]
The issue was caused by the incorrect naming of the variable. The code changed to `if self.mirror_map.Nz == 1:`
